services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: george
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes: # how to store data
      - db:/data/postgres
    ports:
      - "5432:5432" # port 5432[localhost , can be random port] ---> mapping to ---> 5432[actual instance running inside the container] (requests from localhost will be redirected to on the container)
    networks:
      - db
    restart: unless-stopped

  george15-api:
      container_name: george15-api
      image: george15/george15-api
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
      ports:
        - "8088:8080"
      networks:
      - db
      depends_on:
      - db  #  we don't want to start george15-api container unless db (database) container is up and running
      restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: